export const meet_links_data = [
  {
    day: "Mondays",
    meeting: "KhulnaSoft Websites Meeting",
    slack_channel: "#websites",
    slack_link: "https://khulnasoft.slack.com/archives/C015QJKUMPU",
    meeting_minutes: "https://bit.ly/2XK4eQV",
    meeting_link: "https://meet.khulnasoft.com/websites",
    meeting_recordings: "https://www.youtube.com/watch?v=Zba0b0ZojOI&list=PL3A-A6hPO2IO1ZuLj3cbOTdi-hlkF4Lqu",
  },
  {
    day: "Mondays",
    meeting: "WebAssembly Filters Meeting",
    slack_channel: "#wasm",
    slack_link: "https://khulnasoft.slack.com/archives/C012UMS2MCM",
    meeting_minutes: "https://bit.ly/3zGZgGg",
    meeting_link: "https://meet.khulnasoft.com/wasm",
    meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IOur7idhSAUf6hySLn-hdVD",
  },
  {
    day: "Tuesdays",
    meeting: "Meshplay MeshSync/MeshMap Meeting",
    slack_channel: "#meshplay-ci",
    slack_link: "https://khulnasoft.slack.com/archives/C010LFFGFFA",
    meeting_minutes: "https://bit.ly/3aXOaAs",
    meeting_link: "https://meet.khulnasoft.com/meshmap",
    meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day: "Wednesdays",
    meeting: "Meshplay Development Meeting",
    slack_channel: "#meshplay",
    slack_link: "https://khulnasoft.slack.com/archives/CFGG6U10E",
    meeting_minutes: "https://bit.ly/31OGQTk",
    meeting_link: "https://meet.khulnasoft.com/meshplay",
    meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day: "2nd & 4th Thursday",
    meeting: "Meshplay CI Meeting",
    slack_channel: "#meshplay-ci",
    slack_link: "https://khulnasoft.slack.com/archives/C011VPREG2Z",
    meeting_minutes: "https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit",
    meeting_link: "https://meet.khulnasoft.com/meshplay-ci",
    meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IM7rYiKxG4l3eQNc6X3IUex",
  },
  {
    day: "Thursdays",
    meeting: "KhulnaSoft Newcomers' Meeting",
    slack_channel: "#newcomers",
    slack_link: "https://khulnasoft.slack.com/archives/C019426UBNY",
    meeting_minutes: "https://docs.google.com/document/d/1aHarIyIL__HRq_4klYOUsEXP5SQLlmb50W17yKdNmpU/edit#",
    meeting_link: "https://meet.khulnasoft.com/newcomers",
    meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day: "Fridays",
    meeting: "KhulnaSoft Community Meeting",
    slack_channel: "#general",
    slack_link: "https://khulnasoft.slack.com/archives/CDM0ACDM5",
    meeting_minutes: "https://bit.ly/2It7IA4",
    meeting_link: "https://meet.khulnasoft.com/community",
    meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day: "Biweekly Thursday",
    meeting: "Service Mesh Performance Meeting",
    slack_channel: "#performance",
    slack_link: "https://khulnasoft.slack.com/archives/CVBGPTFJN",
    meeting_minutes: "https://bit.ly/3B7uIy9",
    meeting_link: "https://meet.khulnasoft.com/smp",
    meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IPZ3dP6FgZBAA0dZFmmX0kA",
  },
  {
    day: "1st & 3rd Thursday",
    meeting: "CNCF TAG Network Meeting",
    slack_channel: "#tag-network",
    slack_link: "",
    meeting_minutes: "https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#",
    meeting_link: "https://zoom.us/my/cncftagnetwork",
    meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
];
